basePath: /api
definitions:
  req.RequestAddRatePlan:
    properties:
      description:
        type: string
      price:
        type: number
      room_type_code:
        type: string
    type: object
  req.RequestAddStatusBooking:
    properties:
      description:
        type: string
      status_code:
        type: string
      status_name:
        type: string
    required:
    - description
    - status_code
    - status_name
    type: object
  req.RequestDeleteRatePlan:
    properties:
      rate_plan_id:
        type: string
    type: object
  req.RequestGetRatePlan:
    properties:
      rate_plan_id:
        type: string
    type: object
  req.RequestNewPasswordReset:
    properties:
      new_password:
        type: string
      token:
        type: string
    required:
    - new_password
    - token
    type: object
  req.RequestResetPassword:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  req.RequestSignIn:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  req.RequestSignUp:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
    required:
    - email
    - first_name
    - last_name
    - password
    type: object
  req.RequestUpdatePassword:
    properties:
      new_password:
        type: string
      password:
        type: string
    required:
    - new_password
    - password
    type: object
  req.RequestUpdateProfile:
    properties:
      first_name:
        type: string
      last_name:
        type: string
      phone:
        type: string
    type: object
  req.RequestUpdateRatePlan:
    properties:
      description:
        type: string
      price:
        type: number
      rate_plan_id:
        type: string
      room_type_id:
        type: string
    type: object
  res.Response:
    properties:
      data: {}
      message:
        type: string
      status_code:
        type: integer
    type: object
host: https://siphoria-api-production.up.railway.app
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: HOTEL BOOKING API
  version: "1.0"
paths:
  /admin/add-status-booking:
    post:
      consumes:
      - application/json
      parameters:
      - description: status booking
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/req.RequestAddStatusBooking'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/res.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/res.Response'
      summary: Register account Admin
      tags:
      - admin-service
  /auth/change-pwd:
    post:
      consumes:
      - application/json
      parameters:
      - description: account
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/req.RequestUpdatePassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/res.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/res.Response'
      summary: Handle Change Password
      tags:
      - auth-service
  /auth/forgot:
    post:
      consumes:
      - application/json
      parameters:
      - description: account
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/req.RequestResetPassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/res.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/res.Response'
      summary: Send Email To Reset Password
      tags:
      - auth-service
  /auth/login/general:
    post:
      consumes:
      - application/json
      parameters:
      - description: account
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/req.RequestSignIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/res.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/res.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/res.Response'
      summary: Sign In Account
      tags:
      - auth-service
  /auth/refresh-token:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/res.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/res.Response'
      summary: Create access token by refresh token
      tags:
      - auth-service
  /auth/reset:
    post:
      consumes:
      - application/json
      parameters:
      - description: account
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/req.RequestNewPasswordReset'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/res.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/res.Response'
      summary: Handle Reset Password
      tags:
      - auth-service
  /auth/signup:
    post:
      consumes:
      - application/json
      parameters:
      - description: account
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/req.RequestSignUp'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/res.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/res.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/res.Response'
      summary: Create new account
      tags:
      - auth-service
  /auth/verifyemail/:code:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/res.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/res.Response'
      summary: Handle Activate Account
      tags:
      - auth-service
  /hotels/:id:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/res.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/res.Response'
      summary: Get hotel by Id
      tags:
      - hotel-service
  /hotels/search:
    post:
      consumes:
      - application/json
      parameters:
      - description: hotel
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/req.RequestUpdateProfile'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/res.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/res.Response'
      summary: Search Hotel
      tags:
      - hotel-service
  /ratePlan/delete-rateplan:
    post:
      consumes:
      - application/json
      parameters:
      - description: rateplan
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/req.RequestDeleteRatePlan'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/res.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/res.Response'
      summary: Delete rateplan
      tags:
      - rateplan-service
  /ratePlan/rateplan-info:
    post:
      consumes:
      - application/json
      parameters:
      - description: rateplan
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/req.RequestGetRatePlan'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/res.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/res.Response'
      summary: Rateplan info
      tags:
      - rateplan-service
  /ratePlan/rateplans:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/res.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/res.Response'
      summary: Get rateplan list
      tags:
      - rateplan-service
  /ratePlan/save-rateplan:
    post:
      consumes:
      - application/json
      parameters:
      - description: rateplan
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/req.RequestAddRatePlan'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/res.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/res.Response'
      summary: Save rateplan
      tags:
      - rateplan-service
  /ratePlan/update-rateplan:
    post:
      consumes:
      - application/json
      parameters:
      - description: rateplan
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/req.RequestUpdateRatePlan'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/res.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/res.Response'
      summary: Update rateplan
      tags:
      - rateplan-service
  /users/add-to-cart:
    post:
      consumes:
      - application/json
      parameters:
      - description: user
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/req.RequestUpdateProfile'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/res.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/res.Response'
      summary: Add to cart
      tags:
      - user-service
  /users/carts:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/res.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/res.Response'
      summary: Get cart by user
      tags:
      - user-service
  /users/details:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/res.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/res.Response'
      summary: Get Customer Profile
      tags:
      - user-service
  /users/get-rank-available:
    get:
      consumes:
      - application/json
      parameters:
      - description: user
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/req.RequestUpdateProfile'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/res.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/res.Response'
      summary: Get user rank
      tags:
      - user-service
  /users/update-avatar:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/res.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/res.Response'
      summary: Update user's avatar
      tags:
      - user-service
  /users/update-profile:
    patch:
      consumes:
      - application/json
      parameters:
      - description: user
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/req.RequestUpdateProfile'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/res.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/res.Response'
      summary: Update customer profile
      tags:
      - user-service
  /users/update-rank:
    post:
      consumes:
      - application/json
      parameters:
      - description: user
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/req.RequestUpdateProfile'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/res.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/res.Response'
      summary: Update user's rank
      tags:
      - user-service
swagger: "2.0"
